// Generated by CoffeeScript 1.6.3
(function() {
  exports.verboseLevel = 3;

  exports.log = function() {
    if (exports.verboseLevel <= 2) {
      return;
    }
    return console.log.apply(console, arguments);
  };

  exports.error = function() {
    if (exports.verboseLevel <= 0) {
      return;
    }
    return console.error.apply(console, arguments);
  };

  exports.warn = function() {
    if (!exports.verboseLevel <= 1) {
      return;
    }
    return console.warn.apply(console, arguments);
  };

}).call(this);
