// Generated by CoffeeScript 1.6.3
(function() {
  require("coffee-script");

  exports.serializeCallInfo = function(name, count) {
    return {
      name: name,
      count: count
    };
  };

  exports.serializeCallRequest = function(name, args) {
    return {
      name: name,
      args: args
    };
  };

}).call(this);
